filter:
  paths: [src/*]
  excluded_paths: [vendor/*, tests/*]
tools:
  php_sim: true
  php_changetracking: true
  php_mess_detector:
    enabled: true
  php_pdepend: true
  php_analyzer:
    enabled: true
  sensiolabs_security_checker: true
  php_code_sniffer: 
    enabled: true
    config:
      standard: "PSR2"
