<?php $hasIdentity = !is_null($this->identity()); ?>

<ul class="nav navbar-nav">
    <?php foreach ($this->container as $group): ?>
    <li<?= $group->isActive(true) ? ' class="active"' : '' ?>>
        <a href="<?= $group->getHref() ?>"<?= count($group->getPages()) ? ' class="dropdown-toggle" data-toggle="dropdown"' : '' ?>>
            <?= $this->escapeHtml($group->getLabel()); ?><?= count($group->getPages()) ? ' <b class="caret"></b>' : '' ?></a>
        <?php if ($group->getPages()): ?>
        <ul class="dropdown-menu">
            <?php foreach ($group->getPages() as $page): ?>
            <?php if (!$page->get('requires-login') || $hasIdentity): ?>
            <li<?= $page->isActive() ? ' class="active"' : '' ?>>
                <a href="<?= $page->getHref() ?>">
                    <?= $this->escapeHtml($page->getLabel()); ?></a>
            </li>
            <?php endif; ?>
            <?php endforeach; ?>
        </ul>
        <?php endif; ?>
    </li>
    <?php endforeach; ?>
</ul>
