
<h2 class="page-title">Create SCM Project</h2>

<?php
/**
 * @var $form Zend\Form\Form
 */
$form = $this->form;
$form->prepare();
$form->setAttributes(
    [
        'method' => 'POST',
        'action' => '',
        'class' => 'form-horizontal',
        'role' => 'form'
    ]
);
?>

<?= $this->form()->openTag($form) ?>

<div class="form-group">
    <?= $this->bootstrapFormLabel($form->get('name')) ?>
    <div class="col-lg-10">
        <?= $this->bootstrapFormInput($form->get('name')) ?>
        <?= $this->formElementErrors($form->get('name')) ?>
    </div>
</div>

<div class="form-group">
    <?= $this->bootstrapFormLabel($form->get('description')) ?>
    <div class="col-lg-10">
        <?= $this->formTextarea($form->get('description')->setAttribute('class', 'form-control')) ?>
        <?= $this->formElementErrors($form->get('description')) ?>
    </div>
</div><div class="form-group">
    <?= $this->bootstrapFormLabel($form->get('scm')) ?>
    <div class="col-lg-10">
        <?= $this->formSelect($form->get('scm')->setAttribute('class', 'form-control')) ?>
        <?= $this->formElementErrors($form->get('scm')) ?>
    </div>
</div>

<div class="form-group">
    <?= $this->bootstrapFormLabel($form->get('uri')) ?>
    <div class="col-lg-10">
        <?= $this->bootstrapFormInput($form->get('uri')) ?>
        <?= $this->formElementErrors($form->get('uri')) ?>
    </div>
</div>

<div class="text-center">
    <?= $this->formButton($form->get('create')->setAttribute('class', 'btn btn-primary')) ?>
</div>

<?= $this->form()->closeTag() ?>
