
<h2 class="page-title pull-left">Projects</h2>

<?php if ($this->projects): ?>
<span class="pull-right">
    <a class="btn btn-primary" href="<?= $this->url('projects/create') ?>">Create Project</a>
</span>
<div class="clearfix"></div>

<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Description</th>
            <th>Status</th>
            <th>URL</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->projects as $project): ?>
        <tr>
            <td>
                <a href="<?= $this->url('projects/view', ['id' => $project->getId()]) ?>">
                    <?= $project->getId() ?></a>
            </td>
            <td>
                <a href="<?= $this->url('projects/view', ['id' => $project->getId()]) ?>">
                <?= $project->getName() ?></a>
            </td>
            <td><?= $project->getDescription() ?></td>
            <td>
                <span class="label label-success">Success</span>
            </td>
            <td><?= $project->getUri() ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php else: ?>
<div class="clearfix"></div>
<div class="callout callout-warning">
    <h4>You don't have any projects yet!</h4>
    <p>
        Go ahead and <a href="/projects/create">create your first one</a>, or, for more information about how to
        create projects, please checkout the <a href="http://martha-ci.github.io/guide">user guide</a>.
    </p>
</div>
<?php endif; ?>
