
<h2 class="page-title pull-left">Projects</h2>

<span class="pull-right">
    <a class="btn btn-primary" href="<?= $this->url('projects/create') ?>">Create Project</a>
</span>

<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Description</th>
            <th>URL</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->projects as $project): ?>
        <tr>
            <td>
                <a href="<?= $this->url('projects/view', ['id' => $project->getId()]) ?>">
                    <?= $project->getId() ?></a>
            </td>
            <td>
                <a href="<?= $this->url('projects/view', ['id' => $project->getId()]) ?>">
                <?= $project->getName() ?></a>
            </td>
            <td><?= $project->getDescription() ?></td>
            <td><?= $project->getUri() ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>