
<div class="projects-dashboard">
    <div class="row">
        <h2 class="page-title">Recent Builds</h2>
        <?php if (count($this->builds)): ?>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>
                        #
                    </th>
                    <th>
                        Project
                    </th>
                    <th>
                        Status
                    </th>
                    <th>
                        Age
                    </th>
                    <th>
                        Method
                    </th>
                </tr>
            </thead>
            <?php foreach ($this->builds as $build): ?>
            <tr>
                <td>
                    <a href="<?= $this->url('build', ['action' => 'view', 'id' => $build->getId()]) ?>">
                        <?= $build->getId() ?></a>
                </td>
                <td>
                    <a href="<?= $this->url('projects/view', ['id' => $build->getProject()->getId()]) ?>">
                        <?= $build->getProject()->getName() ?></a>
                </td>
                <td>
                    <?= $this->buildStatus($build->getStatus()) ?>
                </td>
                <td>
                    <span title="<?= $build->getCreated()->format('j M Y h:i A') ?>">
                        <?= $this->age($build->getCreated()) ?></span>
                </td>
                <td>
                    <?= $build->getMethod() ?>
                </td>
            </tr>
            <?php endforeach; ?>
            <?php else: ?>
            <div class="callout callout-warning">
                <h4>You don't have any builds yet!</h4>
                <p>
                    For more information about how to setup builds, please checkout the
                    <a href="http://martha-ci.github.io/guide">user guide</a>.
                </p>
            </div>
            <?php endif; ?>
        </table>
    </div>
</div>

